export declare const OnEvent: (topic: string) => MethodDecorator;
export declare const EventTopics: {
    readonly CUSTOMER_CREATED: "customer.created";
    readonly CUSTOMER_UPDATED: "customer.updated";
    readonly CUSTOMER_DELETED: "customer.deleted";
    readonly CUSTOMER_SEGMENT_CHANGED: "segment.changed";
    readonly PRODUCT_CREATED: "product.created";
    readonly PRODUCT_UPDATED: "product.updated";
    readonly PRODUCT_DELETED: "product.deleted";
    readonly PRODUCT_STOCK_CHANGED: "product.stock.changed";
    readonly PLAN_CREATED: "plan.created";
    readonly PLAN_UPDATED: "plan.updated";
    readonly PLAN_DELETED: "plan.deleted";
    readonly FEATURE_CREATED: "feature.created";
    readonly FEATURE_UPDATED: "feature.updated";
    readonly FEATURE_DELETED: "feature.deleted";
    readonly ORDER_CREATED: "order.created";
    readonly ORDER_UPDATED: "order.updated";
    readonly ORDER_CANCELLED: "order.cancelled";
    readonly ORDER_COMPLETED: "order.completed";
    readonly PAYMENT_INITIATED: "payment.initiated";
    readonly PAYMENT_SUCCESS: "payment.success";
    readonly PAYMENT_FAILED: "payment.failed";
    readonly INVOICE_CREATED: "invoice.created";
    readonly INVOICE_UPDATED: "invoice.updated";
    readonly INVOICE_OVERDUE: "invoice.overdue";
    readonly INVENTORY_CREATED: "inventory.created";
    readonly INVENTORY_ADJUSTED: "inventory.adjusted";
    readonly INVENTORY_RESERVED: "inventory.reserved";
    readonly INVENTORY_RELEASED: "inventory.released";
    readonly INVENTORY_LOW_STOCK: "inventory.low_stock";
};
